// SPDX-License-Identifier: MIT
pragma solidity ^0.8.4;

import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";

import "src/factory.sol";

// Interface for interaction with the parent Factory contract.
interface IFactory {
    function updateStatus(address _adminAddress, uint256 _nonce) external;
}

// This contract is intended to be deployed only via Factory.sol.
// Each Child contract represents a single transfer/invoice
// instance and acts as a one-time payment intermediary.
contract Child {
    using SafeERC20 for IERC20;

    // Indicates whether the transfer was already completed.
    bool transferMade;

    // The user who initiated the transfer
    // and deployed this Child contract through the Factory.
    address public immutable ADMIN_ADDRESS;

    // Unique (for the user) transfer identifier generated by Factory.
    uint256 public immutable ID_NONCE;

    // Expected transfer amount from the payer.
    uint256 public immutable TRANSFER_SUM;

    // USDT contract address provided by the Factory contract.
    address public immutable USDT_ADDRESS;

    // Parent Factory contract address.
    address public immutable FACTORY_ADDRESS;

    // Initializes a new Child transfer contract with the data
    // provided by the depolyer - Factory contract.
    constructor(address _adminAddress, uint256 _transferSum, uint256 _idNonce, address _USDTAddress) {
        ADMIN_ADDRESS = _adminAddress;
        TRANSFER_SUM = _transferSum;
        ID_NONCE = _idNonce;
        FACTORY_ADDRESS = msg.sender;
        _USDTAddress = USDT_ADDRESS;
    }

    // This function is called by the payer to complete the transfer.
    //
    // Before execution, the payer must approve this contract
    // to spend the required amount of tokens on their behalf.
    //
    // After successful execution:
    // 1. The transfer is marked as completed locally, preventing any further deposits.
    // 2. The parent Factory contract is notified.
    function Deposit(uint256 amount) external {
        require(transferMade == false, "Transfer already made");
        require(amount == TRANSFER_SUM, "Deposit the right amount");
        IERC20(USDT_ADDRESS).safeTransferFrom(msg.sender, ADMIN_ADDRESS, amount);
        transferMade = true;
        IFactory(FACTORY_ADDRESS).updateStatus(ADMIN_ADDRESS, ID_NONCE);
    }
}
